Added dev version of install script

diff --git a/install-development b/install-development
--- a/install-development
+++ b/install-development
@@ -22,33 +22,56 @@
 #  ./install --phpize /usr/bin/phpize5.6 --php-config /usr/bin/php-config5.6
 
 CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+PARSER_DIR=${CURRENT_DIR}/parser
+
+# Set defaults
+ARCH=
+CC=${CC:-}
 
 GCC_BIN=$(command -v gcc 2>/dev/null)
-RE2C_BIN=${RE2C_BIN:-$(command -v re2c 2>/dev/null)}
+CLANG_BIN=$(command -v clang 2>/dev/null)
+RE2C_BIN=$(command -v re2c 2>/dev/null)
+CCACHE_BIN=$(command -v ccache 2>/dev/null)
+PHPIZE_BIN=$(command -v phpize 2>/dev/null)
+PHPCONFIG_BIN=$(command -v php-config 2>/dev/null)
 
 if [ x"$RE2C_BIN" = x ]; then
   echo -e "error: unable to locate the re2c"
   exit 2
 fi
 
-if [ x"$GCC_BIN" = x ]; then
-	echo -e "error: unable to locate the gcc"
+if [ x"$CC" == x ]; then
+	if [ x"$GCC_BIN" != x ]; then
+		export CC="gcc"
+	else
+		if [ x"$CLANG_BIN" != x ]; then
+			export CC="clang"
+		fi
+	fi
+fi
+
+if [ x"$CC" == x ]; then
+	echo -e "error: unable to locate the compiler"
 	exit 1
 fi
 
-# Check best compilation flags for compiller
-export CC=gcc
-export CFLAGS="-march=native -mtune=native -O2 -fomit-frame-pointer"
-export CPPFLAGS="-DZEPHIR_PARSER_RELEASE"
+if [ x"$CC" == xclang ]; then
+	export CFLAGS="-g3 -O0 -fcolor-diagnostics"
+else
+	export CFLAGS="-g3 -O0 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"
+fi
 
-# Set defaults
-PHPIZE_BIN=$(command -v phpize 2>/dev/null)
-PHPCONFIG_BIN=$(command -v php-config 2>/dev/null)
+if [ x"$CCACHE_BIN" != x ]; then
+	export CC="ccache ${CC}"
+fi
+
+export CPPFLAGS="-DZEPHIR_PARSER_RELEASE"
 
 # Translate long options to short
 for arg in "$@"; do
   shift
   case "$arg" in
+    "--arch") set -- "$@" "-a" ;;
     "--phpize") set -- "$@" "-i" ;;
     "--php-config") set -- "$@" "-c" ;;
     *) set -- "$@" "$arg"
@@ -56,12 +79,23 @@ for arg in "$@"; do
 done
 
 # Options switcher
-while getopts i:c: opts; do
+while getopts a:i:c: opts; do
    case ${opts} in
+      a) ARCH=${OPTARG} ;;
       i) PHPIZE_BIN=${OPTARG} ;;
       c) PHPCONFIG_BIN=${OPTARG} ;;
    esac
 done
+
+if [ x"$PHPIZE_BIN" = x ]; then
+  echo -e "error: unable to locate the phpize"
+  exit 1
+fi
+
+if [ x"$PHPCONFIG_BIN" = x ]; then
+  echo -e "error: unable to locate the php-config"
+  exit 1
+fi
 
 PHP_FULL_VERSION=`${PHPCONFIG_BIN} --version`
 
@@ -75,27 +109,7 @@ if [ "${PHP_FULL_VERSION:0:3}" == "5.3" ]; then
 	exit 1
 fi
 
-# Detect possible flags
-echo "int main() {}" > t.c
-gcc ${CFLAGS} t.c -o t 2> t.t
-if [ $? != 0 ]; then
-	chmod +x gcccpuopt
-	BFLAGS=`./gcccpuopt`
-	export CFLAGS="-O2 -fomit-frame-pointer $BFLAGS"
-	gcc ${CFLAGS} t.c -o t 2> t.t
-	if [ $? != 0 ]; then
-		export CFLAGS="-O2"
-	fi
-fi
-
-if [ $(gcc -dumpversion | cut -f1 -d.) -ge 4 ]; then
-	gcc ${CFLAGS} -fvisibility=hidden t.c -o t 2> t.t
-	export CFLAGS="$CFLAGS -fvisibility=hidden"
-fi
-
-rm -f t.t t.c t
-
-cd ${CURRENT_DIR}/parser
+cd ${PARSER_DIR}
 
 # Cleanup
 rm -f \
@@ -118,33 +132,30 @@ if [ ! -f lemon ]; then
 	${CC} lemon.c -o lemon
 fi
 
-echo -e "Generating PHP 5 parser..."
-./lemon -s parser.php5.lemon
-if [ ! -f parser.php5.c ]; then
-	echo "error: couldn't generate parser"
-	exit 2
+if [ "${PHP_FULL_VERSION:0:1}" == "5" ]; then
+	PHP_VERSION="php5"
+else
+	PHP_VERSION="php7"
 fi
-echo
 
-./lemon -s parser.php7.lemon
-if [ ! -f parser.php7.c ]; then
+echo -e "Generating parser..."
+./lemon -s parser.${PHP_VERSION}.lemon
+
+if [ ! -f parser.${PHP_VERSION}.c ]; then
 	echo "error: couldn't generate parser"
-	exit 2
+	exit 1
 fi
-echo
 
 echo "#include <php.h>" > parser.c
-echo "#if PHP_VERSION_ID < 70000" >> parser.c
-cat parser.php5.c >> parser.c
-echo "#else" >> parser.c
-cat parser.php7.c >> parser.c
-echo "#endif" >> parser.c
+cat parser.${PHP_VERSION}.c >> parser.c
 cat base.c >> parser.c
 
 sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
 sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
 
 cd ${CURRENT_DIR}
+
+echo
 
 # Clean current compilation
 if [ -f Makefile ]; then
@@ -154,38 +165,25 @@ fi
 
 # Perform the compilation
 ${PHPIZE_BIN}
-./configure --silent --with-php-config=${PHPCONFIG_BIN} --enable-zephir_parser
+./configure --with-php-config=${PHPCONFIG_BIN} --enable-zephir_parser
 make -s  -j"$(getconf _NPROCESSORS_ONLN)"
 make test
 
 echo
 
-make -s install
+sudo make install
 
 echo
 
 # Clean current compilation
 if [ -f Makefile ]; then
-	make -s clean
+	make clean
 	${PHPIZE_BIN} --clean
 fi
 
-
 cd ${CURRENT_DIR}/parser
 
-# Cleanup
-rm -f \
-	*.o \
-	*.lo \
-	lemon \
-	scanner.c \
-	parser.c \
-	parser.php5.c \
-	parser.php5.h \
-	parser.php5.out \
-	parser.php7.c \
-	parser.php7.h \
-	parser.php7.out
+rm -f *.o *.lo
 
 echo -e "\nThanks for compiling Zephir Parser!\nBuild succeed: Please restart your web server to complete the installation\n"
 
