Added set -e to intsall scripts

diff --git a/install-development b/install-development
--- a/install-development
+++ b/install-development
@@ -28,6 +28,9 @@
 #  Build and install extension:
 #  ./install-development --phpize /usr/bin/phpize5.6 --php-config /usr/bin/php-config5.6 --install
 
+# Exit immediately if a command exits with a non-zero status.
+set -e
+
 export ZEND_DONT_UNLOAD_MODULES=1
 export USE_ZEND_ALLOC=0
 
@@ -133,7 +136,7 @@ rm -f \
 
 rm -rf .libs
 
-${RE2C_BIN} --no-generation-date -b -o scanner.c scanner.re
+${RE2C_BIN} --no-generation-date -o scanner.c scanner.re
 
 # Compile lemon
 ${CC} lemon.c -o lemon
