Generating PHP parser

diff --git a/parser/build-linux b/parser/build-linux
--- a/parser/build-linux
+++ b/parser/build-linux
@@ -7,6 +7,8 @@ CLANG_BIN=${CLANG_BIN:-$(command -v clang 2>/dev/null)}
 
 RE2C_BIN=${RE2C_BIN:-$(command -v re2c 2>/dev/null)}
 
+rm -f *.o *.lo
+
 if [ x"$CC" != x ]; then
     if [ x"$GCC_BIN" != x ]; then
         export CC="gcc"
@@ -29,9 +31,23 @@ fi
 
 ${RE2C_BIN} -o scanner.c scanner.re
 
-rm -f *.o *.lo
-
 # Compile lemon
 if [ ! -f lemon ]; then
     ${CC} lemon.c -o lemon
 fi
+
+echo -e "Generating PHP 5 parser..."
+./lemon -s parser.php5.lemon
+if [ ! -f parser.php5.c ]; then
+    echo "error: couldn't generate parser"
+    exit 2
+fi
+echo
+
+echo -e "Generating PHP 7 parser..."
+./lemon -s parser.php7.lemon
+if [ ! -f parser.php7.c ]; then
+    echo "error: couldn't generate parser"
+    exit 2
+fi
+echo
